# Generated by Django 5.2.6 on 2025-11-19 16:57

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import landingPgApp.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('short_description', models.CharField(max_length=100, verbose_name='Descrição Curta')),
                ('location', models.CharField(max_length=50, verbose_name='Localização')),
                ('total_units', models.PositiveIntegerField(blank=True, verbose_name='Total de Unidades')),
                ('is_last_units', models.BooleanField(default=False)),
                ('yt_video_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empreendimento',
                'verbose_name_plural': 'Empreendimentos',
            },
        ),
        migrations.CreateModel(
            name='VentureStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Status do Empreendimento',
                'verbose_name_plural': 'Status dos Empreendimentos',
            },
        ),
        migrations.CreateModel(
            name='VentureAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='Icone')),
                ('value', models.CharField(max_length=100, verbose_name='Valor')),
                ('span', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Espaços')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='landingPgApp.venture')),
            ],
        ),
        migrations.CreateModel(
            name='VentureAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='landingPgApp.venture')),
            ],
        ),
        migrations.CreateModel(
            name='VentureFloorPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descriptionList', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='landingPgApp.venture')),
            ],
        ),
        migrations.CreateModel(
            name='VentureHeroHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Rótulo')),
                ('info', models.CharField(max_length=50, verbose_name='Informação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_highlights', to='landingPgApp.venture')),
            ],
        ),
        migrations.CreateModel(
            name='VentureImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=landingPgApp.models.venture_image_upload_to, verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Imagem de Capa')),
                ('is_high_light', models.BooleanField(default=False, verbose_name='Imagem destacada')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingPgApp.ventureareas')),
                ('floorPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingPgApp.venturefloorplans')),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='landingPgApp.venture', verbose_name='Empreendimento')),
            ],
            options={
                'verbose_name': 'Imagem do Empreendimento',
                'verbose_name_plural': 'Imagens dos Empreendimentos',
            },
        ),
        migrations.AddField(
            model_name='venturefloorplans',
            name='imgages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingPgApp.ventureimages'),
        ),
        migrations.CreateModel(
            name='VentureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='landingPgApp.venture')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingPgApp.ventureimages')),
            ],
        ),
        migrations.AddField(
            model_name='ventureareas',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingPgApp.ventureimages'),
        ),
        migrations.AddField(
            model_name='venture',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventures', to='landingPgApp.venturestatus'),
        ),
    ]
