# Generated by Django 5.2.6 on 2025-11-19 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venturecategory',
            options={'verbose_name': 'Categoria do Empreendimento', 'verbose_name_plural': 'Categorias dos Empreendimentos'},
        ),
        migrations.AlterField(
            model_name='venturecategory',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landingPgApp.ventureimages'),
        ),
        migrations.AlterField(
            model_name='venturecategory',
            name='venture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='landingPgApp.venture'),
        ),
    ]
