# Generated by Django 5.2.6 on 2025-11-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0002_alter_venturecategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventureareas',
            name='images',
        ),
        migrations.RemoveField(
            model_name='venturecategory',
            name='images',
        ),
        migrations.RemoveField(
            model_name='venturefloorplans',
            name='imgages',
        ),
    ]
