# Generated by Django 5.2.6 on 2025-11-20 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0003_remove_ventureareas_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventureimages',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landingPgApp.ventureareas'),
        ),
        migrations.AlterField(
            model_name='ventureimages',
            name='floorPlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landingPgApp.venturefloorplans'),
        ),
    ]
