# Generated by Django 5.2.6 on 2025-11-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0004_alter_ventureimages_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventureamenities',
            options={'verbose_name': 'Comodidade do Empreendimento', 'verbose_name_plural': 'Comodidades do Empreendimento'},
        ),
        migrations.AlterModelOptions(
            name='ventureareas',
            options={'verbose_name': 'Área do Empreendimento', 'verbose_name_plural': 'Áreas do Empreendimento'},
        ),
        migrations.AlterModelOptions(
            name='venturefloorplans',
            options={'verbose_name': 'Planta do Empreendimento', 'verbose_name_plural': 'Plantas do Empreendimento'},
        ),
        migrations.AlterModelOptions(
            name='ventureherohighlight',
            options={'verbose_name': 'Destaque do Banner do Empreendimento', 'verbose_name_plural': 'Destaques do Banner dos Empreendimentos'},
        ),
        migrations.AddField(
            model_name='venture',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Empreendimento Ativo?'),
        ),
        migrations.AddField(
            model_name='ventureimages',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Imagem Ativa?'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='is_last_units',
            field=models.BooleanField(default=False, verbose_name='Últimas Unidades?'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='yt_video_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID do Vídeo do YouTube'),
        ),
    ]
