# Generated by Django 5.2.6 on 2025-11-20 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0005_alter_ventureamenities_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venturecategory',
            name='venture',
        ),
        migrations.AddField(
            model_name='venture',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventures', to='landingPgApp.venturecategory'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventures', to='landingPgApp.venturestatus'),
        ),
    ]
