# Generated by Django 5.2.6 on 2025-11-21 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0006_remove_venturecategory_venture_venture_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventureimages',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='landingPgApp.ventureareas'),
        ),
        migrations.AlterField(
            model_name='ventureimages',
            name='floorPlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='landingPgApp.venturefloorplans'),
        ),
    ]
