# Generated by Django 5.2.6 on 2025-12-19 19:13

import django.db.models.deletion
import django_ckeditor_5.fields
import landingPgApp.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0007_alter_ventureimages_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag do Blog',
                'verbose_name_plural': 'Tags do Blog',
            },
        ),
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('cover_image', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=landingPgApp.models.blog_article_image_upload_to, verbose_name='Imagem da Capa')),
                ('is_highlight', models.BooleanField(default=False, verbose_name='Artigo em Destaque?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Artigo Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='landingPgApp.blogtag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Artigo do Blog',
                'verbose_name_plural': 'Artigos do Blog',
            },
        ),
    ]
