# Generated by Django 5.2.6 on 2025-12-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0008_blogtag_blogarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='short_description',
            field=models.CharField(default='Pellentesque vestibulum ultricies libero, sit amet sodales nisi blandit ac. Ut sed vulputate lectus. Fusce non tellus elementum, condimentum massa vitae', max_length=300, verbose_name='Descrição Curta'),
            preserve_default=False,
        ),
    ]
