# Generated by Django 5.2.6 on 2025-12-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0009_blogarticle_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='venture',
            name='homepage_highlight',
            field=models.BooleanField(default=False, verbose_name='Destaque na Página Inicial?'),
        ),
    ]
