# Generated by Django 5.2.6 on 2026-02-18 17:44

import landingPgApp.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0010_venture_homepage_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=landingPgApp.models.site_image_upload_to, verbose_name='Imagem')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('page', models.CharField(choices=[('home', 'Home'), ('ventures', 'Empreendimentos'), ('venture_detail', 'Detalhe do Empreendimento'), ('blog', 'Blog'), ('blog_article', 'Artigo do Blog'), ('contact', 'Contato'), ('other', 'Outra Página')], db_index=True, default='home', max_length=30, verbose_name='Página do Site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imagem do Site',
                'verbose_name_plural': 'Imagens do Site',
            },
        ),
        migrations.AlterModelOptions(
            name='blogarticle',
            options={'verbose_name': 'Artigo do Blog', 'verbose_name_plural': '..Artigos do Blog'},
        ),
        migrations.AlterModelOptions(
            name='venture',
            options={'verbose_name': 'Empreendimento', 'verbose_name_plural': '..Empreendimentos'},
        ),
    ]
