# Generated by Django 5.2.6 on 2026-04-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0011_siteimages_alter_blogarticle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimages',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Imagem Ativa?'),
        ),
    ]
