# Generated by Django 5.2.6 on 2026-04-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0012_siteimages_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteimages',
            options={'verbose_name': 'Imagem do Site', 'verbose_name_plural': '..Imagens do Site'},
        ),
        migrations.AddField(
            model_name='siteimages',
            name='is_desktop',
            field=models.BooleanField(default=True, verbose_name='Imagem para Desktop?'),
        ),
        migrations.AddField(
            model_name='siteimages',
            name='is_mobile',
            field=models.BooleanField(default=False, verbose_name='Imagem para Mobile?'),
        ),
    ]
