# Generated by Django 5.2.6 on 2026-04-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0013_alter_siteimages_options_siteimages_is_desktop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimages',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('ventures', 'Nossas Obras'), ('about_us', 'Nossa História'), ('your_dreams', 'Seus Sonhos'), ('blog', 'Blog')], db_index=True, default='home', max_length=30, verbose_name='Página do Site'),
        ),
    ]
