# Generated by Django 5.2.6 on 2026-04-06 20:05

import landingPgApp.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0014_alter_siteimages_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('video_url', models.URLField(max_length=500, verbose_name='URL do Vídeo')),
                ('cover_image', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=landingPgApp.models.blog_article_image_upload_to, verbose_name='Imagem da Capa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Vídeo Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vídeo Instrucional',
                'verbose_name_plural': '..Vídeos Instrucionais',
            },
        ),
    ]
