# Generated by Django 5.2.6 on 2026-04-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0016_ebook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venture',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Empreendimento', 'verbose_name_plural': '..Empreendimentos'},
        ),
        migrations.AlterModelOptions(
            name='venturestatus',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Status do Empreendimento', 'verbose_name_plural': 'Status dos Empreendimentos'},
        ),
        migrations.AddField(
            model_name='venture',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='venturestatus',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
