# Generated by Django 5.2.6 on 2026-04-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0017_alter_venture_options_alter_venturestatus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venture',
            name='is_active',
        ),
        migrations.AddField(
            model_name='venture',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visível?'),
        ),
        migrations.AddField(
            model_name='venturestatus',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visível?'),
        ),
    ]
