# Generated by Django 5.2.6 on 2026-04-09 16:04

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0018_remove_venture_is_active_venture_is_visible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSolicitationTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80, verbose_name='Descrição')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Texto do Termo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Texto Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Termo de Solicitação de Serviço',
                'verbose_name_plural': 'Termos de Solicitação de Serviço',
            },
        ),
        migrations.AlterModelOptions(
            name='instructionalvideo',
            options={'verbose_name': 'Vídeo Instrucional', 'verbose_name_plural': 'Vídeos Instrucionais'},
        ),
        migrations.AlterModelOptions(
            name='siteimages',
            options={'verbose_name': 'Imagem do Site', 'verbose_name_plural': 'Imagens do Site'},
        ),
    ]
