# Generated by Django 5.2.6 on 2026-04-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0019_servicesolicitationterm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimages',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('ventures', 'Nossas Obras'), ('about_us', 'Nossa História'), ('your_dreams', 'Seus Sonhos'), ('blog', 'Blog'), ('service_solicitation', 'Solicitação de Serviços')], db_index=True, default='home', max_length=30, verbose_name='Página do Site'),
        ),
    ]
