# Generated by Django 5.2.6 on 2026-04-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPgApp', '0020_alter_siteimages_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='venture',
            name='accepts_service_solicitation',
            field=models.BooleanField(default=True, verbose_name='Aceitando Assistência Técnica?'),
        ),
    ]
